- entropicranksdir: '/home/ubuntu/imputeDisk/01-workspace/00-temp/Entropic_Ranks_docker/'
  datatable: 'TestDataGSE69486/smallDataTable.txt'
  vector: 'TestDataGSE69486/population_vector.txt'
  origin: 'null'
  granularity: '1'
  supervised: 'FALSE'
  logfile: 'FALSE'
  plots: 'TRUE'
  outputs: 'TRUE'
  islogged: 'TRUE'
  logbase: '2'
  hugefeaturelist: 'FALSE'
